#ifndef MODBUSPROTOCOL_GLOBAL_H
#define MODBUSPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSPROTOCOL_LIBRARY)
#  define MODBUSPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODBUSPROTOCOL_GLOBAL_H
