#ifndef MODBUSSERIALPORT_GLOBAL_H
#define MODBUSSERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSSERIALPORT_LIBRARY)
#  define MODBUSSERIALPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSSERIALPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODBUSSERIALPORT_GLOBAL_H
